// SPDX-FileCopyrightText: 2026 SecretAgent12
// SPDX-License-Identifier: LGPL-3.0-only

package com.hbm.backport.compat;

import com.hbm.backport.InteractionResults;
import com.hbm.backport.storage.TagValueInput;
import com.hbm.backport.storage.TagValueOutput;
import com.hbm.backport.storage.ValueInput;
import com.hbm.backport.storage.ValueOutput;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.ItemInteractionResult;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Explosion;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.LevelReader;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;

/**
 * Generated by the backport: net.minecraft.world.level.block.DoublePlantBlock with the 26.x hook
 * signatures (getLightBlock, useItemOn, useWithoutItem, updateShape, neighborChanged, entityInside, onRemove, getAnalogOutputSignal, propagatesSkylightDown, onExplosionHit, wasExploded, getCloneItemStack, appendHoverText). See the pass for how the bridges work.
 */
public abstract class DoublePlantBlockCompat extends net.minecraft.world.level.block.DoublePlantBlock {

    public DoublePlantBlockCompat(net.minecraft.world.level.block.state.BlockBehaviour.Properties a0) {
        super(a0);
    }

    @Override
    protected int getLightBlock(BlockState state, BlockGetter level, BlockPos pos) {
        int dampening = getLightDampening(state);
        return dampening >= 0 ? dampening : super.getLightBlock(state, level, pos);
    }

    protected int getLightDampening(BlockState state) {
        return -1;
    }

    @Override
    protected final ItemInteractionResult useItemOn(ItemStack stack, BlockState state, Level level, BlockPos pos, Player player, InteractionHand hand, BlockHitResult hit) {
        return InteractionResults.toItemInteraction(backport$useItemOn(stack, state, level, pos, player, hand, hit));
    }

    protected com.hbm.backport.InteractionResult backport$useItemOn(ItemStack stack, BlockState state, Level level, BlockPos pos, Player player, InteractionHand hand, BlockHitResult hit) {
        return InteractionResults.fromItemInteraction(super.useItemOn(stack, state, level, pos, player, hand, hit));
    }

    @Override
    protected final net.minecraft.world.InteractionResult useWithoutItem(BlockState state, Level level, BlockPos pos, Player player, BlockHitResult hit) {
        return InteractionResults.toVanilla(backport$useWithoutItem(state, level, pos, player, hit));
    }

    protected com.hbm.backport.InteractionResult backport$useWithoutItem(BlockState state, Level level, BlockPos pos, Player player, BlockHitResult hit) {
        return InteractionResults.fromVanilla(super.useWithoutItem(state, level, pos, player, hit));
    }

    @Override
    protected final BlockState updateShape(BlockState state, Direction direction, BlockState neighbor, LevelAccessor level, BlockPos pos, BlockPos neighborPos) {
        return updateShape(state, level, com.hbm.backport.ScheduledTickAccess.of(level), pos, direction, neighborPos, neighbor, level.getRandom());
    }

    protected BlockState updateShape(BlockState state, LevelReader level, com.hbm.backport.ScheduledTickAccess ticks, BlockPos pos, Direction direction, BlockPos neighborPos, BlockState neighbor, RandomSource random) {
        return super.updateShape(state, direction, neighbor, (LevelAccessor) level, pos, neighborPos);
    }

    @Override
    protected final void neighborChanged(BlockState state, Level level, BlockPos pos, Block block, BlockPos fromPos, boolean moved) {
        BlockPos previous = BACKPORT$FROM.get();
        BACKPORT$FROM.set(fromPos);
        try {
            neighborChanged(state, level, pos, block, (com.hbm.backport.Orientation) null, moved);
        } finally {
            BACKPORT$FROM.set(previous);
        }
    }

    /** 1.21.1's fromPos, for the vanilla super call only; 26.x code never sees it. */
    private static final ThreadLocal<BlockPos> BACKPORT$FROM = new ThreadLocal<>();

    protected void neighborChanged(BlockState state, Level level, BlockPos pos, Block block, @Nullable com.hbm.backport.Orientation orientation, boolean moved) {
        BlockPos from = BACKPORT$FROM.get();
        super.neighborChanged(state, level, pos, block, from != null ? from : pos, moved);
    }

    @Override
    protected final void entityInside(BlockState state, Level level, BlockPos pos, Entity entity) {
        entityInside(state, level, pos, entity, com.hbm.backport.InsideBlockEffectApplier.immediate(entity), true);
    }

    protected void entityInside(BlockState state, Level level, BlockPos pos, Entity entity, com.hbm.backport.InsideBlockEffectApplier effects, boolean precise) {
        super.entityInside(state, level, pos, entity);
    }

    @Override
    protected final void onRemove(BlockState state, Level level, BlockPos pos, BlockState newState, boolean moved) {
        boolean changed = !state.is(newState.getBlock());
        if (changed && level.getBlockEntity(pos) instanceof com.hbm.backport.BlockEntityCompat be) be.preRemoveSideEffects(pos, state);
        super.onRemove(state, level, pos, newState, moved);
        if (changed && level instanceof ServerLevel server) affectNeighborsAfterRemoval(state, server, pos, moved);
    }

    /** 26.x's half of 1.21.1's onRemove that runs after the block is gone. */
    protected void affectNeighborsAfterRemoval(BlockState state, ServerLevel level, BlockPos pos, boolean moved) {}

    @Override
    protected final int getAnalogOutputSignal(BlockState state, Level level, BlockPos pos) {
        return getAnalogOutputSignal(state, level, pos, (Direction) null);
    }

    /** 26.x also passes the side the comparator reads from; 1.21.1 does not know it, so it is null. */
    protected int getAnalogOutputSignal(BlockState state, Level level, BlockPos pos, @Nullable Direction direction) {
        return super.getAnalogOutputSignal(state, level, pos);
    }

    @Override
    protected final boolean propagatesSkylightDown(BlockState state, BlockGetter level, BlockPos pos) {
        return propagatesSkylightDown(state);
    }

    protected boolean propagatesSkylightDown(BlockState state) {
        return super.propagatesSkylightDown(state, net.minecraft.world.level.EmptyBlockGetter.INSTANCE, BlockPos.ZERO);
    }

    @Override
    protected final void onExplosionHit(BlockState state, Level level, BlockPos pos, Explosion explosion, BiConsumer<ItemStack, BlockPos> drops) {
        if (level instanceof ServerLevel server) onExplosionHit(state, server, pos, explosion, drops);
        else super.onExplosionHit(state, level, pos, explosion, drops);
    }

    protected void onExplosionHit(BlockState state, ServerLevel level, BlockPos pos, Explosion explosion, BiConsumer<ItemStack, BlockPos> drops) {
        super.onExplosionHit(state, level, pos, explosion, drops);
    }

    @Override
    public final void wasExploded(Level level, BlockPos pos, Explosion explosion) {
        if (level instanceof ServerLevel server) wasExploded(server, pos, explosion);
    }

    public void wasExploded(ServerLevel level, BlockPos pos, Explosion explosion) {
        super.wasExploded(level, pos, explosion);
    }

    @Override
    public final ItemStack getCloneItemStack(LevelReader level, BlockPos pos, BlockState state) {
        return getCloneItemStack(level, pos, state, false);
    }

    protected ItemStack getCloneItemStack(LevelReader level, BlockPos pos, BlockState state, boolean includeData) {
        return super.getCloneItemStack(level, pos, state);
    }

    @Override
    public final void appendHoverText(ItemStack stack, Item.TooltipContext context, List<Component> tooltip, TooltipFlag flag) {
        appendHoverText(stack, context, com.hbm.backport.TooltipDisplay.DEFAULT, tooltip::add, flag);
    }

    public void appendHoverText(ItemStack stack, Item.TooltipContext context, com.hbm.backport.TooltipDisplay display, Consumer<Component> tooltip, TooltipFlag flag) {
        List<Component> lines = new ArrayList<>();
        super.appendHoverText(stack, context, lines, flag);
        lines.forEach(tooltip);
    }
}
