// SPDX-FileCopyrightText: 2026 SecretAgent12
// SPDX-License-Identifier: LGPL-3.0-only

package com.hbm.backport.compat;

import com.hbm.backport.InteractionResults;
import com.hbm.backport.storage.TagValueInput;
import com.hbm.backport.storage.TagValueOutput;
import com.hbm.backport.storage.ValueInput;
import com.hbm.backport.storage.ValueOutput;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.ItemInteractionResult;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Explosion;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.LevelReader;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;

/**
 * Generated by the backport: net.minecraft.world.item.Item with the 26.x hook
 * signatures (use, useOn, interactLivingEntity, onItemUseFirst, getCraftingRemainingItem, releaseUsing, hurtEnemy, inventoryTick, appendHoverText). See the pass for how the bridges work.
 */
public abstract class ItemCompat extends net.minecraft.world.item.Item {

    public ItemCompat(net.minecraft.world.item.Item.Properties a0) {
        super(a0);
    }

    @Override
    public final InteractionResultHolder<ItemStack> use(Level level, Player player, InteractionHand hand) {
        return InteractionResults.toHolder(backport$use(level, player, hand), player.getItemInHand(hand));
    }

    public com.hbm.backport.InteractionResult backport$use(Level level, Player player, InteractionHand hand) {
        return InteractionResults.fromHolder(super.use(level, player, hand));
    }

    @Override
    public final net.minecraft.world.InteractionResult useOn(UseOnContext context) {
        return InteractionResults.toVanilla(backport$useOn(context));
    }

    public com.hbm.backport.InteractionResult backport$useOn(UseOnContext context) {
        return InteractionResults.fromVanilla(super.useOn(context));
    }

    @Override
    public final net.minecraft.world.InteractionResult interactLivingEntity(ItemStack stack, Player player, LivingEntity target, InteractionHand hand) {
        return InteractionResults.toVanilla(backport$interactLivingEntity(stack, player, target, hand));
    }

    public com.hbm.backport.InteractionResult backport$interactLivingEntity(ItemStack stack, Player player, LivingEntity target, InteractionHand hand) {
        return InteractionResults.fromVanilla(super.interactLivingEntity(stack, player, target, hand));
    }

    @Override
    public final net.minecraft.world.InteractionResult onItemUseFirst(ItemStack stack, UseOnContext context) {
        return InteractionResults.toVanilla(backport$onItemUseFirst(stack, context));
    }

    public com.hbm.backport.InteractionResult backport$onItemUseFirst(ItemStack stack, UseOnContext context) {
        return InteractionResults.fromVanilla(super.onItemUseFirst(stack, context));
    }

    @Override
    public final ItemStack getCraftingRemainingItem(ItemStack stack) {
        com.hbm.backport.ItemStackTemplate r = getCraftingRemainder(stack);
        return r == null ? ItemStack.EMPTY : r.create();
    }

    @Override
    public final boolean hasCraftingRemainingItem(ItemStack stack) {
        return getCraftingRemainder(stack) != null;
    }

    public @Nullable com.hbm.backport.ItemStackTemplate getCraftingRemainder(com.hbm.backport.ItemInstance instance) {
        return getCraftingRemainder();
    }

    public @Nullable com.hbm.backport.ItemStackTemplate getCraftingRemainder() {
        Item r = getCraftingRemainingItem();
        return r == null ? null : new com.hbm.backport.ItemStackTemplate(r);
    }

    @Override
    public final void releaseUsing(ItemStack stack, Level level, LivingEntity entity, int timeLeft) {
        backport$releaseUsing(stack, level, entity, timeLeft);
    }

    public boolean backport$releaseUsing(ItemStack stack, Level level, LivingEntity entity, int timeLeft) {
        super.releaseUsing(stack, level, entity, timeLeft);
        return false;
    }

    @Override
    public final boolean hurtEnemy(ItemStack stack, LivingEntity target, LivingEntity attacker) {
        backport$hurtEnemy(stack, target, attacker);
        // 26.x: a hit counts (ITEM_USED stat, postHurtEnemy) only with the WEAPON component,
        // which MixinItemStackWeapon checks; 1.21.1's Item.hurtEnemy default is false as well
        return false;
    }

    public void backport$hurtEnemy(ItemStack stack, LivingEntity target, LivingEntity attacker) {
        super.hurtEnemy(stack, target, attacker);
    }

    @Override
    public final void inventoryTick(ItemStack stack, Level level, Entity entity, int slot, boolean selected) {
        if (level instanceof ServerLevel server) inventoryTick(stack, server, entity, InteractionResults.slotOf(stack, entity, selected));
    }

    public void inventoryTick(ItemStack stack, ServerLevel level, Entity entity, @Nullable EquipmentSlot slot) {}

    @Override
    public final void appendHoverText(ItemStack stack, Item.TooltipContext context, List<Component> tooltip, TooltipFlag flag) {
        appendHoverText(stack, context, com.hbm.backport.TooltipDisplay.DEFAULT, tooltip::add, flag);
    }

    public void appendHoverText(ItemStack stack, Item.TooltipContext context, com.hbm.backport.TooltipDisplay display, Consumer<Component> tooltip, TooltipFlag flag) {
        List<Component> lines = new ArrayList<>();
        super.appendHoverText(stack, context, lines, flag);
        lines.forEach(tooltip);
    }

    /** backport: 26.x gives items in #minecraft:swords the sword actions (sweep); 1.21.1 NeoForge only
     * SwordItem. Unverified: inferred from ntm-next tagging its swords, not from 26.x source. */
    @Override
    public boolean canPerformAction(ItemStack stack, net.neoforged.neoforge.common.ItemAbility ability) {
        return stack.is(net.minecraft.tags.ItemTags.SWORDS)
                        && net.neoforged.neoforge.common.ItemAbilities.DEFAULT_SWORD_ACTIONS.contains(ability)
                || super.canPerformAction(stack, ability);
    }
}
