// SPDX-FileCopyrightText: 2026 SecretAgent12
// SPDX-License-Identifier: LGPL-3.0-only

package com.hbm.backport.compat;

import com.hbm.backport.InteractionResults;
import com.hbm.backport.storage.TagValueInput;
import com.hbm.backport.storage.TagValueOutput;
import com.hbm.backport.storage.ValueInput;
import com.hbm.backport.storage.ValueOutput;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.ItemInteractionResult;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Explosion;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.LevelReader;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;

/**
 * Generated by the backport: net.minecraft.world.effect.MobEffect with the 26.x hook
 * signatures (applyEffectTick). See the pass for how the bridges work.
 */
public abstract class MobEffectCompat extends net.minecraft.world.effect.MobEffect {

    protected MobEffectCompat(net.minecraft.world.effect.MobEffectCategory a0, int a1) {
        super(a0, a1);
    }

    protected MobEffectCompat(net.minecraft.world.effect.MobEffectCategory a0, int a1, net.minecraft.core.particles.ParticleOptions a2) {
        super(a0, a1, a2);
    }

    @Override
    public final boolean applyEffectTick(LivingEntity entity, int amplifier) {
        if (entity.level() instanceof ServerLevel server) return applyEffectTick(server, entity, amplifier);
        return true;
    }

    public boolean applyEffectTick(ServerLevel level, LivingEntity entity, int amplifier) {
        return super.applyEffectTick(entity, amplifier);
    }
}
