// SPDX-FileCopyrightText: 2026 SecretAgent12
// SPDX-License-Identifier: LGPL-3.0-only

package com.hbm.backport.compat;

import com.hbm.backport.InteractionResults;
import com.hbm.backport.storage.TagValueInput;
import com.hbm.backport.storage.TagValueOutput;
import com.hbm.backport.storage.ValueInput;
import com.hbm.backport.storage.ValueOutput;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.ItemInteractionResult;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Explosion;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.LevelReader;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;

/**
 * Generated by the backport: net.minecraft.world.entity.PathfinderMob with the 26.x hook
 * signatures (readAdditionalSaveData, addAdditionalSaveData, hurt, lerpTo, customServerAiStep, doHurtTarget, mobInteract). See the pass for how the bridges work.
 */
public abstract class PathfinderMobCompat extends net.minecraft.world.entity.PathfinderMob {

    protected PathfinderMobCompat(net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.PathfinderMob> a0, net.minecraft.world.level.Level a1) {
        super(a0, a1);
    }

    @Override
    public final void readAdditionalSaveData(CompoundTag tag) {
        readAdditionalSaveData(TagValueInput.of(tag, registryAccess()));
    }

    protected void readAdditionalSaveData(ValueInput input) {
        super.readAdditionalSaveData(TagValueInput.tagOf(input));
    }

    @Override
    public final void addAdditionalSaveData(CompoundTag tag) {
        addAdditionalSaveData(TagValueOutput.wrap(tag, registryAccess()));
    }

    protected void addAdditionalSaveData(ValueOutput output) {
        super.addAdditionalSaveData(TagValueOutput.tagOf(output));
    }

    @Override
    public final boolean hurt(DamageSource source, float amount) {
        if (level() instanceof ServerLevel server) return hurtServer(server, source, amount);
        return super.hurt(source, amount);
    }

    public boolean hurtServer(ServerLevel level, DamageSource source, float amount) {
        return super.hurt(source, amount);
    }

    @Override
    public void lerpTo(double x, double y, double z, float yRot, float xRot, int steps) {
        com.hbm.backport.InterpolationHandler h = getInterpolation();
        if (h != null) h.interpolateTo(new Vec3(x, y, z), yRot, xRot);
        else super.lerpTo(x, y, z, yRot, xRot, steps);
    }

    public com.hbm.backport.@Nullable InterpolationHandler getInterpolation() {
        return null;
    }

    @Override
    protected final void customServerAiStep() {
        customServerAiStep((ServerLevel) level());
    }

    protected void customServerAiStep(ServerLevel level) {
        super.customServerAiStep();
    }

    @Override
    public final boolean doHurtTarget(Entity target) {
        return level() instanceof ServerLevel server ? doHurtTarget(server, target) : super.doHurtTarget(target);
    }

    public boolean doHurtTarget(ServerLevel level, Entity target) {
        return super.doHurtTarget(target);
    }

    @Override
    protected final net.minecraft.world.InteractionResult mobInteract(Player player, InteractionHand hand) {
        return InteractionResults.toVanilla(backport$mobInteract(player, hand));
    }

    protected com.hbm.backport.InteractionResult backport$mobInteract(Player player, InteractionHand hand) {
        return InteractionResults.fromVanilla(super.mobInteract(player, hand));
    }
}
